name: Deploy to flyio

on:
  push:
    branches:
      - main

env:
  ILLA_GOOGLE_MAP_KEY: ${{ secrets.ILLA_GOOGLE_MAP_KEY }}
  ILLA_MIXPANEL_API_KEY: ${{ secrets.ILLA_MIXPANEL_API_KEY }}
  ILLA_AMPLITUDE_API_KEY: ${{ secrets.ILLA_AMPLITUDE_API_KEY }}
  ILLA_MUI_LICENSE: ${{ secrets.ILLA_MUI_LICENSE }}
  ILLA_SENTRY_AUTH_TOKEN: ${{ secrets.ILLA_SENTRY_AUTH_TOKEN }}

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    environment:
      name: "production"
    env:
      ILLA_API_BASE_URL: ${{ vars.ILLA_API_BASE_URL }}
      ILLA_APP_ENV: ${{ vars.ILLA_APP_ENV }}
      ILLA_BUILDER_URL: ${{ vars.ILLA_BUILDER_URL }}
      ILLA_CLOUD_URL: ${{ vars.ILLA_CLOUD_URL }}
      ILLA_MARKET_URL: ${{ vars.ILLA_MARKET_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build website
        run: |
          echo "Building for $GITHUB_REF_NAME branch,ILLA APP ENV is $ILLA_APP_ENV"
          pnpm build-cloud

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
